version: '3.8'

services:
  webapp:
    build: .
    command: python webapp_server.py
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - WEBAPP_URL=${WEBAPP_URL}
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  bot:
    build: .
    command: python enhanced_bot.py
    depends_on:
      - webapp
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - VET_SERVICE_PHONE=${VET_SERVICE_PHONE}
      - VET_SERVICE_EMAIL=${VET_SERVICE_EMAIL}
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  data:

